import { Games } from "./app/layout/models/game";
export const sample_games: Games[] = [
    {
      id: '1',  
      name: "Unicorn Racing Extravaganza",
      description: "Race majestic unicorns through enchanted forests and mystical meadows in this whimsical racing game!",
      price: "$19.99",
      stars: 5.6,
      imageUrl: "./store-app/src/assets/img/games/1.png",
      tags: ["Racing", "Fantasy"],
      origins: ["USA"]
    },
    { "id": '2',
      "name": "Zombie Dance Party",
      "description": "Join the undead on the dance floor for a groovy night of brain-munching beats and monster moves!",
      "price": "$14.99",
      "stars": 5.6,
      "imageUrl": "./store-app/src/assets/img/games/2.png",
      "tags": ["Dancing", "Horror"],
      "origins": ["UK"]
    },
    { "id": '3',
      "name": "Banana Peel Bonanza",
      "description": "Slip, slide, and hurl bananas at your opponents in this wacky multiplayer mayhem!",
      "price": "$9.99",
      "stars": 5.3,
      "imageUrl": "./store-app/src/assets/img/games/3.png",
      "tags": ["Multiplayer", "Comedy"],
      "origins": ["Canada"]
    },

    { "id": '4',
      "name": "Penguin Plumber Panic",
      "description": "Help penguins fix leaky pipes and navigate treacherous waters in this icy adventure!",
      "price": "$24.99",
      "stars": 3.6,
      "imageUrl": "./store-app/src/assets/img/games/4.png",
      "tags": ["Puzzle", "Adventure"],
      "origins": ["Antarctica"]
    },
    { "id": '5',
      "name": "Squirrel Simulator 3000",
      "description": "Experience life as a furry woodland creature as you scurry, stash, and steal your way through the forest!",
      "price": "$29.99",
      "stars": 5.9,
      "imageUrl": "./store-app/src/assets/img/games/5.png",
      "tags": ["Simulation", "Animal"],
      "origins": ["Europe"]
    },

    { "id": '6',
        "name": "Kitty Cat Chaos",
        "description": "Embrace your inner feline as you embark on a mischievous journey through a world ruled by cats!",
        "price": "$19.99",
        "stars": 2.6,
        "imageUrl": "./store-app/src/assets/img/games/6.png",
        "tags": ["Adventure", "Animal"],
        "origins": ["Europe"]
      },
      { "id": '7',
        "name": "Superhero Chicken Squad",
        "description": "Join a team of heroic chickens as they peck, scratch, and cluck their way to justice!",
        "price": "$12.99",
        "stars": 5.5,
        "imageUrl": "./store-app/src/assets/img/games/7.png",
        "tags": ["Action", "Comedy"],
        "origins": ["USA"]
      },
      { "id": '8',
        "name": "Robot Roller Derby Rumble",
        "description": "Customize your mechanical derby bot and roll, dash, and slam your way to victory in this futuristic sport!",
        "price": "$34.99",
        "stars": 8.6,
        "imageUrl": "./store-app/src/assets/img/games/8.png",
        "tags": ["Sports", "Futuristic"],
        "origins": ["Japan"]
      },
      { "id": '9',
        "name": "Alien Disco Invasion",
        "description": "Beam aboard the mothership for an out-of-this-world dance party with extraterrestrial beats and neon lights!",
        "price": "$21.99",
        "stars": 9.9,
        "imageUrl": "./store-app/src/assets/img/games/9.png",
        "tags": ["Music", "Sci-Fi"],
        "origins": ["Mars"]
      },
      { "id": '10',
        "name": "Pirate Penguin Plunder",
        "description": "Hoist the sails and join a crew of penguin pirates as they search for buried fish and buried treasure!",
        "price": "$26.99",
        "stars": 8.6,
        "imageUrl": "./store-app/src/assets/img/games/10.png",
        "tags": ["Adventure", "Pirate"],
        "origins": ["Antarctica"]
      },
      { "id": '11',
        "name": "Ninja Noodle Nonsense",
        "description": "Slice, dice, and slurp your way through a deliciously chaotic world of flying noodles and ninja antics!",
        "price": "$17.99",
        "stars": 4.2,
        "imageUrl": "./store-app/src/assets/img/games/11.png",
        "tags": ["Action", "Food"],
        "origins": ["China"]
      },
      { "id": '12',
        "name": "Space Sloth Saga",
        "description": "Embark on a slow-motion adventure through the cosmos as a laid-back sloth on a quest for cosmic enlightenment!",
        "price": "$29.99",
        "stars": 5.6,
        "imageUrl": "./store-app/src/assets/img/games/12.png",
        "tags": ["Adventure", "Sci-Fi"],
        "origins": ["Galaxy"]
      },
      { "id": '13',
        "name": "Vampire Vacation",
        "description": "Sink your fangs into a bloody good time as you navigate a world of sun, sand, and supernatural romance!",
        "price": "$23.99",
        "stars": 5.1,
        "imageUrl": "./store-app/src/assets/img/games/13.png",
        "tags": ["Simulation", "Horror"],
        "origins": ["Transylvania"]
      },
      { "id": '14',
        "name": "Monster Munchies Mayhem",
        "description": "Join a hungry horde of monsters as they chomp, chew, and gobble their way through a city-sized buffet!",
        "price": "$18.99",
        "stars": 2.8,
        "imageUrl": "./store-app/src/assets/img/games/14.png",
        "tags": ["Action", "Food"],
        "origins": ["Monster Island"]
      },
      { "id": '15',
        "name": "Funky Frog Frenzy",
        "description": "Hop, leap, and ribbit your way through a swampy wonderland of funky beats and amphibious adventure!",
        "price": "$16.99",
        "stars": 9.7,
        "imageUrl": "./store-app/src/assets/img/games/15.png",
        "tags": ["Adventure", "Music"],
        "origins": ["Swamp"]
      },      
      
  ];
  